#!/usr/bin/env python3
"""Render agent-generated BYJU's v2 hi-fi SVGs into gallery beat PNGs (regenerated/)."""

from __future__ import annotations

import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SLUG = "points-marketplace-foundational"
INBOX = Path.home() / "Desktop/points-marketplace-wireframes-export/agent-generated"
SRC = ROOT / "assets" / "case-studies" / SLUG / "hifi-v2-src"
DEST = ROOT / "assets" / "case-studies" / SLUG / "regenerated"
GALLERY = ROOT / "assets" / "case-studies" / SLUG / "gallery"
BEATS = ROOT / "assets" / "case-studies" / SLUG / "beats"

CANVAS_W, CANVAS_H = 1200, 960

_INVALID_XML = re.compile(r"[\x00-\x08\x0B\x0C\x0E-\x1F]")


def _sanitize_svg(path: Path) -> None:
    """Make SVG safe for browser XML parsers (no control chars in comments or text)."""
    data = path.read_bytes()
    try:
        text = data.decode("utf-8")
    except UnicodeDecodeError:
        text = data.decode("latin-1")
    text = text.replace("\x14", " - ")
    text = _INVALID_XML.sub(" ", text)

    def _fix_comment(match: re.Match[str]) -> str:
        body = match.group(1)
        body = _INVALID_XML.sub(" ", body)
        body = body.replace("\u2014", "-").replace("\u2013", "-").replace("\xb7", "-")
        return f"<!--{body}-->"

    text = re.sub(r"<!--(.*?)-->", _fix_comment, text, flags=re.S)
    text = text.replace("\u00b7", "&#183;").replace("\xb7", "&#183;")
    text = re.sub(
        r">([^<]+)</text>",
        lambda m: ">" + m.group(1).replace("'", "&apos;") + "</text>",
        text,
    )
    if not text.lstrip().startswith("<?xml"):
        text = '<?xml version="1.0" encoding="UTF-8"?>\n' + text
    path.write_text(text, encoding="utf-8", newline="\n")


# Gallery filename → v2 SVG (beat narrative preserved)
BEAT_MAP = [
    ("marketplace-prototype.png", "mobile-marketplace-landing-v2.svg", "portrait"),
    ("synthesis-trends.png", "points-wallet-ledger-v2.svg", "portrait"),
    ("design-stimulus-figma.png", "ui-component-sheet.svg", "wide"),
    ("user-testing-stimulus.png", "redeem-confirmation.svg", "portrait"),
    ("onboarding-recommendations.png", "onboarding-flow-3-steps.svg", "wide"),
]


def _ql_raster(svg: Path, out_dir: Path, max_px: int) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    for stale in out_dir.glob(f"{svg.name}.png"):
        stale.unlink()
    result = subprocess.run(
        ["qlmanage", "-t", "-s", str(max_px), "-o", str(out_dir), str(svg)],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(f"qlmanage failed for {svg.name}: {result.stderr}")
    generated = out_dir / f"{svg.name}.png"
    if not generated.is_file():
        raise FileNotFoundError(f"Missing raster: {generated}")
    return generated


def _fit_canvas(src: Path, dest: Path, mode: str) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    tmp = dest.parent / f".{dest.stem}.raw.png"
    shutil.copy2(src, tmp)
    if mode == "portrait":
        # Long phone screens: fit inside 1200×960
        subprocess.run(["sips", "-Z", str(CANVAS_H), str(tmp)], check=True, capture_output=True)
    else:
        subprocess.run(["sips", "-z", str(CANVAS_H), str(CANVAS_W), str(tmp)], check=True, capture_output=True)
    shutil.copy2(tmp, dest)
    tmp.unlink(missing_ok=True)
    print(f"  → {dest.relative_to(ROOT)} ({mode})")


def sync_sources() -> None:
    if not INBOX.is_dir():
        print(f"Inbox missing: {INBOX}", file=sys.stderr)
        sys.exit(1)
    SRC.mkdir(parents=True, exist_ok=True)
    for _, svg_name, _ in BEAT_MAP:
        src = INBOX / svg_name
        if not src.is_file():
            print(f"Missing {src}", file=sys.stderr)
            sys.exit(1)
        shutil.copy2(src, SRC / svg_name)
        _sanitize_svg(SRC / svg_name)
    print(f"Synced + sanitized {len(BEAT_MAP)} SVGs → {SRC.relative_to(ROOT)}/")


def main() -> int:
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--sync-inbox",
        action="store_true",
        help="Copy from Desktop agent-generated inbox (default: use repo hifi-v2-src only)",
    )
    args = parser.parse_args()
    if args.sync_inbox:
        sync_sources()
    elif not SRC.is_dir():
        print(f"Missing {SRC}", file=sys.stderr)
        return 1
    tmp_dir = ROOT / ".cache" / "byjus-hifi-v2-raster"
    tmp_dir.mkdir(parents=True, exist_ok=True)
    print(f"Rendering v2 hi-fi → {DEST.relative_to(ROOT)}/")
    for out_name, svg_name, mode in BEAT_MAP:
        svg = SRC / svg_name
        _sanitize_svg(svg)
        max_px = CANVAS_H if mode == "portrait" else CANVAS_W
        raw = _ql_raster(svg, tmp_dir, max_px)
        _fit_canvas(raw, DEST / out_name, mode)
        shutil.copy2(DEST / out_name, GALLERY / out_name)
        at2x = BEATS / out_name.replace(".png", "@2x.png")
        subprocess.run(
            ["sips", "-z", str(CANVAS_H * 2), str(CANVAS_W * 2), str(DEST / out_name), "--out", str(at2x)],
            check=True,
            capture_output=True,
        )
    print("Done.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
